# Generated by Django 5.2 on 2025-05-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_purchase_price_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', 'description'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'description', 'category', 'price'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
